### ISSUE TITLE
Typo on Several Titles

### ISSUE THREAD

**Issue by wisn** [arkwrn/arkwrn.github.io#2]
Some posts use `Pyhton` instead of `Python`.

https://arkwrn.github.io/Belajar-Python-1/
https://arkwrn.github.io/Belajar-Python-2/
https://arkwrn.github.io/Belajar-Python-3/
https://arkwrn.github.io/Belajar-Python-4/

**Comment by arkrwn** [comment]
thanks gan, fixed asap.
